CoderDojoPotsdam/intro

- _data/tutorials.yml
- dahlem.html
Add dahlem.html and add scratch to tutorials.yml
> Add dhallem.html and add scratch to tutorials.yml

- _data/tutorials.yml
- dahlem.html
Blockly-Games description and fixed link to CoderDojo Dahlem
> Blockly-Games description

- _data/tutorials.yml
change German to English in English tag
@jccabrejas, you can merge :)
> translate to English

- _docs/Branches.md
This documents how to use the branches.
> document branch policy

- dahlem.html
- potsdam.html
> use relative urls in dojo pages

- .gitignore
- _config.yml
- _includes/tutorial.html
- _layouts/overview.html
- css/deactivate-offline.css
- index.html
#28 This are the changes to serve the site from the local server of the server branch
> Server master

- _data/tutorials.yml
- JS Hero
- OpenTechSchool
- Khan Academy
> added JavaScript Tutorials

- _includes/footer.html
> Report a problem link

- _includes/footer.html
Added a PR for the following:
In order to improve the interaction with the users, please add a "report problem" to the footer of the page.
[Add "report problem" to overview pages](https://github.com/CoderDojoPotsdam/intro/issues/52)
Here is a gif to show the changes:
> Add 'report problems' to overview pages - Issue #52

- README.md
- badges for docker build
- badge for offline server with link to server branch
- link to website
> describe more in README landing page

- _docs/README.md
This splits up adding a link to a offline tutorial and adding the contents to a branch.
> Describe offline branch modification

- CONTRIBUTING.md
See http://makeapullrequest.com/
> Add contributing help

- js-beginners/README.md
- js-beginners/index.html
Issue for this pull request:   #49
**Problem to solve:** js-beginners tutorial was not present in the offline version
**Solution chosen:** Added js-beginners files to the offline version
**Notes:** Other folders in the offline section contained source code, however after searching the repo I did not find the source code for the js-beginners tutorial and thus there is only a README and the index present in the folder. These details were not made clear in the original request, so if the source code is available please let me know and I will insert it.
Also, I was unclear if modifying tutorials.yml in the master branch is also needed, since the issue only called for the modification of the offline branch. 
Please let me know if there are any issues.
> Added js-beginners tutorial to offline branch

- dahlem-2.html
This should make your dahlem page look a little better and easier to read.
> Rename dahlem.html to dahlem-2.html

- _data/tutorials.yml
Issue for this pull request:   #49
**Problem to solve:** Offline js-tutorial was not made available.
**Solution chosen:** Modified tutorials.yml to include offline js-beginners tutorial.
> Modified tutorials.yml to include offline js-beginners tutorial

- _docs/OverviewPages.md
- _docs/README.md
It is not clear how to add new overview pages.
Describe more in detail how to write overview pages.
> Document overview

- _layouts/overview.html
> add overview structure

- js-beginners/index.html
Issue for this pull request:  #49  
The index file did not use the local content
redirect to local content
This fixes #49
> redirect to offline tutorial

- css/overview.css
Issue for this pull request:  #29  
Offline tutorials can not be distinguished from online tutorials
Give offline tutorials a green background
> fix #29 - green offline color

- _layouts/overview.html
- css/overview.css
- dahlem.html
- potsdam.html
**Problem to solve:** Add link to dojo page in header 
**Solution chosen:** Created homepage variables in the headers and made it accessible in _layout/overview.html
> added links to the titles

- README.md
Issue for this pull request: #34   
We want people to know what this is for.
Describe three use cases we thought of.
> Describe use

- _includes/category.html
- _includes/footer.html
- _includes/tutorial.html
- _layouts/overview.html
- css/overview.css
> More styling

- potsdam.html
Issue for this pull request: #80  
Scratch should be displayed.
ADD scratch
> add scratch to potsdam.html, fix #80

- _data/tutorials.yml
- _docs/README.md
- _includes/tutorial.html
- potsdam.html
Issue for this pull request: #81   
- Python Kurs hinzufügen
- Den deutschen Kurs nicht bei anderen Sprachen anzeigen.
- Tutorials.yml verändert
- if-Block in die _include/tutorial getan
- dokumentiert, wie man das benutzt
> add Python Kurs

- js/find_lan_servers.js
The error message was a little off
use correct attribute
Before: Checking offline server availability of Himbeere at undefined
After: Checking offline server availability of Himbeere at http://[fe80::7703:af9b:c5c3:9e77]:25444/announce/info
> show offline server address

- _data/categories.yml
- _data/tutorials.yml
- potsdam.html
Issue for this pull request: #2  
There are more tutorials we can use
Add some of them
> add new tutorials for Potsdam

- _docs/README.md
> fix spelling mistakes

- _includes/category.html
- _includes/tutorial.html
- _layouts/overview.html
- css/overview.css
> Added some spacing and CD colors

- index.html
- potsdam.html
Issue for this pull request:  #93 
Es gibt andere Dojos in Potsdam
Name ändern
> Dojo Potsdam zu @HPI umbenennen - #93

- _data/tutorials.yml
- potsdam.html
> Programmieren mit der Maus hinzugefügt

- _data/tutorials.yml
- potsdam.html
Ich habe eine Bot-Umgebung für Paper.io geschieben.
Ich möchte, dass andere die finden.
Tutorial zu den HPI-Sachen hinzufügen.
> add paper-io-bot
